// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQfCyWw9KTAQTWOyoTsJ80uOZP0F64wA',
    appId: '1:96021417055:web:034fe62758345f690e1fea',
    messagingSenderId: '96021417055',
    projectId: 'monie-4d954',
    authDomain: 'monie-4d954.firebaseapp.com',
    storageBucket: 'monie-4d954.firebasestorage.app',
    measurementId: 'G-R0CPXZPZPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5OormMn2LAfowawty4T4N6JbiSmWqp1g',
    appId: '1:96021417055:android:13f000629d7014c90e1fea',
    messagingSenderId: '96021417055',
    projectId: 'monie-4d954',
    storageBucket: 'monie-4d954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKTZ1BDYQhX4Yj-By2vLTh_9Xqv3mfVqk',
    appId: '1:96021417055:ios:263774de0af9073e0e1fea',
    messagingSenderId: '96021417055',
    projectId: 'monie-4d954',
    storageBucket: 'monie-4d954.firebasestorage.app',
    iosBundleId: 'com.example.monie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKTZ1BDYQhX4Yj-By2vLTh_9Xqv3mfVqk',
    appId: '1:96021417055:ios:263774de0af9073e0e1fea',
    messagingSenderId: '96021417055',
    projectId: 'monie-4d954',
    storageBucket: 'monie-4d954.firebasestorage.app',
    iosBundleId: 'com.example.monie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnQfCyWw9KTAQTWOyoTsJ80uOZP0F64wA',
    appId: '1:96021417055:web:5a7e5dd308a2321e0e1fea',
    messagingSenderId: '96021417055',
    projectId: 'monie-4d954',
    authDomain: 'monie-4d954.firebaseapp.com',
    storageBucket: 'monie-4d954.firebasestorage.app',
    measurementId: 'G-10BF7B4E1Y',
  );
}
