// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvi6Cpy73m4IKQsAnBfvC76Uui_Fhyew',
    appId: '1:61128521700:web:7423d9238a2d6f4c37f9f1',
    messagingSenderId: '61128521700',
    projectId: 'monie-d2a2a',
    authDomain: 'monie-d2a2a.firebaseapp.com',
    storageBucket: 'monie-d2a2a.firebasestorage.app',
    measurementId: 'G-X1378WRP9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlCGjf6M_2EqNb3nQbSzQ0nlnqm1GMt8',
    appId: '1:61128521700:android:05a4b751b676c34337f9f1',
    messagingSenderId: '61128521700',
    projectId: 'monie-d2a2a',
    storageBucket: 'monie-d2a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGO5edoAe5p29Ik8321ZxFBQwiy2bjGE',
    appId: '1:61128521700:ios:f0a6571462b75fa737f9f1',
    messagingSenderId: '61128521700',
    projectId: 'monie-d2a2a',
    storageBucket: 'monie-d2a2a.firebasestorage.app',
    iosBundleId: 'com.tadyuh.monie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGO5edoAe5p29Ik8321ZxFBQwiy2bjGE',
    appId: '1:61128521700:ios:f0a6571462b75fa737f9f1',
    messagingSenderId: '61128521700',
    projectId: 'monie-d2a2a',
    storageBucket: 'monie-d2a2a.firebasestorage.app',
    iosBundleId: 'com.tadyuh.monie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvi6Cpy73m4IKQsAnBfvC76Uui_Fhyew',
    appId: '1:61128521700:web:2d517cbaa1bd87f137f9f1',
    messagingSenderId: '61128521700',
    projectId: 'monie-d2a2a',
    authDomain: 'monie-d2a2a.firebaseapp.com',
    storageBucket: 'monie-d2a2a.firebasestorage.app',
    measurementId: 'G-N439TCJPCB',
  );
}
